### ISSUE TITLE
Missing pak3 files from CD install

### ISSUE THREAD

**Issue by tomwilde** [DrBeef/RTCWQuest#11]
hi,

I've installed using the CD and I'm missing sp_pak3.pk3 and sp_pak4.pk3.

I assume I'm missing some official patches?

thanks

Tom

**Comment by baggyg** [comment]
yes you need to make sure the game is fully updated, and then you should have the extra paks

**Comment by tomwilde** [comment]
thanks baggyg :)


So to help others out - go here: https://www.pcgamingwiki.com/wiki/Return_to_Castle_Wolfenstein

you'll need 1.32 (http://wolfenstein4ever.de/index.php/downloads/viewdownload/7-rtcw-patches/115-rtcw-patch-win-1-32-full)

and also 1.42d (http://www.markshan.com/knightmare/downloads.htm)

good luck!

**Comment by DrBeef** [comment]
Just came here to say thanks @tomwilde for taking the trouble to come back to this and post your solution so that others can benefit, good work 👍
