### ISSUE TITLE
After finish first mission - black screen

### ISSUE THREAD

**Issue by DavidJelinek** [DrBeef/RTCWQuest#2]
I have finished first mission, I have seen statistics and Exit and then black screen.  No enter for next mission.

**Comment by T-Thurow** [comment]
I had the same issue. 
Solved it by overwriting pak0.pk3 with the one from the from the RTCW game files. 
I overlooked the file since in the Instructions on https://www.rtcwquest.com/ it isn't formated into the list but the line above.
@DavidJelinek maybe you made the same mistake?

**Comment by baggyg** [comment]
After testing this was found to be where the user had copied everything from their RTCW PC install except the pak0.pk3 file. If you are having this issue please ensure that the file is copied across correctly (overwriting the existing one). 

@T-Thurow Good point about the website. I have moved it down so it looks more like a list now.
