### ISSUE TITLE
Whenever enemy shoots, player gun angles up ward

### ISSUE THREAD

**Issue by drowhunter** [DrBeef/RTCWQuest#3]
I played the current version of the game today for the first time.  I have installed all of the full game pak files

This behavior occurs.

I am using the laser sight, and every time the enemy shoots my gun points towards the ceiling

**Comment by drowhunter** [comment]
Seems to only affect the pistol

**Comment by jarpy** [comment]
Confirmed for me as well. Recoil of enemy pistols appears to be applied to the player's pistol. Very interesting bug!

**Comment by drowhunter** [comment]
Finally some confirmation! How has everyone missed this?

Its the only standout bug to me

**Comment by baggyg** [comment]
Ah that's interesting. I had always thought it meant the gun angles were moved. I never realised you meant it was just the recoil.

**Comment by DrBeef** [comment]
This will be fixed in v1.1.7 dropping very soon

**Comment by drowhunter** [comment]
sweeeeet

**Comment by jarpy** [comment]
> How has everyone missed this?

They probably go straight to the MP 40 and never look back. Also, you'll only notice when the enemies themselves have pistols, which I assume happens less as the game progresses. (It's been... a while since I played it last.)

> This will be fixed in v1.1.7 dropping very soon

Oustanding! Thank you for everything, @DrBeef.
